//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerMessage
    {
        public int Id { get; set; }
        public string texto { get; set; }
        public System.DateTime fecha { get; set; }
        public long timestamp { get; set; }
        public bool ok { get; set; }
    }
}
